Repository netlify/functions.netlify.com, pull requests merged in 2021-02, with the labels that each got.

#68 hardcode the root url for sitemap
  src/_data/site.js
Labels: bug, type: bug

#70 Create a featured section and move down all examples with the search
  .eleventy.js
  src/_includes/layouts/example.njk
  src/_includes/layouts/examples.njk
  src/assets/css/_main.scss
  src/assets/js/scripts.js
  src/examples/airtable-get-request-(single-record-response-with-record-id-in-query-string-or-first-20-without).md
  src/examples/create-react-app-lambda.md
  src/examples/netlify-functions-crud-app-with-fauna.md
Labels: type: feature

#73 [FIX] Update wrong code url
  src/examples/ifttt-to-flick-instagram-make-new-github-post.md
Labels: type: bug

#71 Add large Twitter summary image to top level pages, but not examples
  .eleventy.js
  src/_includes/layouts/default.njk
  src/_includes/layouts/example.njk
  src/_includes/layouts/form.njk
  src/_includes/layouts/tutorials.njk
  src/assets/images/logos/logo-large-card.png
  src/assets/js/scripts.js
  src/examples/examples.json
  src/robots.njk
Labels: type: chore

#74 replace large card with official image
  .eleventy.js
  src/assets/images/logos/netlify-functions-og-card.png
Labels: type: chore
